BEGIN;

-- 1. BASE SETUP (Creación de tablas si no existen)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Tabla Sectores
CREATE TABLE IF NOT EXISTS public.sectores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL UNIQUE,
  color varchar(7) DEFAULT '#6B7280',
  activo boolean DEFAULT true,
  orden_visualizacion integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- Poblar Sectores (Upsert)
INSERT INTO public.sectores (nombre, color, activo, orden_visualizacion)
VALUES
  ('Diseño Gráfico', '#f97316', true, 1),
  ('Taller de Imprenta', '#0ea5e9', true, 2),
  ('Taller Gráfico', '#6366f1', true, 3),
  ('Instalaciones', '#a855f7', true, 4),
  ('Metalúrgica', '#ec4899', true, 5),
  ('Mostrador', '#10b981', true, 6),
  ('Caja', '#facc15', true, 7)
ON CONFLICT (nombre) DO UPDATE
SET
  color = EXCLUDED.color,
  activo = EXCLUDED.activo,
  orden_visualizacion = EXCLUDED.orden_visualizacion;

-- Tabla Usuarios (Estructura base)
CREATE TABLE IF NOT EXISTS public.usuarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  rol text NOT NULL DEFAULT 'empleado',
  last_seen timestamptz DEFAULT now()
);

-- 2. APLICAR ACTUALIZACIONES (Patch 20241205)

-- Agregar columna sector_id
ALTER TABLE public.usuarios
ADD COLUMN IF NOT EXISTS sector_id integer REFERENCES public.sectores(id) ON DELETE SET NULL;

-- Eliminar constraint anterior de roles si existe
ALTER TABLE public.usuarios DROP CONSTRAINT IF EXISTS usuarios_rol_check;

-- Migrar datos existentes (si los hubiera)
UPDATE public.usuarios SET rol = 'admin' WHERE rol = 'administracion';
UPDATE public.usuarios SET rol = 'empleado' WHERE rol IN ('taller', 'mostrador');

-- Agregar constraint con nuevos roles
ALTER TABLE public.usuarios
ADD CONSTRAINT usuarios_rol_check CHECK (rol IN ('admin', 'empleado'));

-- 3. ACTUALIZAR FUNCIONES

-- Función Login Actualizada
DROP FUNCTION IF EXISTS public.login_usuario(text, text);

CREATE OR REPLACE FUNCTION public.login_usuario(p_usuario text, p_password text)
RETURNS TABLE (id integer, nombre text, rol text, sector_id integer)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  user_rec public.usuarios%ROWTYPE;
BEGIN
  SELECT *
    INTO user_rec
    FROM public.usuarios
   WHERE lower(nombre) = lower(p_usuario)
   LIMIT 1;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  IF crypt(p_password, user_rec.password_hash) = user_rec.password_hash THEN
    RETURN QUERY SELECT user_rec.id, user_rec.nombre, user_rec.rol, user_rec.sector_id;
  END IF;
END;
$$;

-- Otorgar permisos
GRANT EXECUTE ON FUNCTION public.login_usuario(text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.login_usuario(text, text) TO authenticated;

-- 4. USUARIO DE PRUEBA (Solo si no existe admin)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.usuarios WHERE rol = 'admin') THEN
    INSERT INTO public.usuarios (nombre, password_hash, rol)
    VALUES ('admin', crypt('admin123', gen_salt('bf')), 'admin');
  END IF;
END
$$;

COMMIT;
