BEGIN;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =========================
-- Core reference tables
-- =========================

CREATE TABLE IF NOT EXISTS public.usuarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  rol text NOT NULL CHECK (rol IN ('administracion','taller','mostrador')),
  last_seen timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sectores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL UNIQUE,
  color varchar(7) DEFAULT '#6B7280',
  activo boolean DEFAULT true,
  orden_visualizacion integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.materiales (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text UNIQUE,
  descripcion text NOT NULL
);

-- =========================
-- Operaciones
-- =========================

CREATE TABLE IF NOT EXISTS public.ordenes_trabajo (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_op varchar(255) NOT NULL,
  cliente varchar(255) NOT NULL,
  descripcion text,
  fecha_entrega date NOT NULL,
  estado varchar(50) NOT NULL DEFAULT 'Pendiente',
  prioridad varchar(50) NOT NULL DEFAULT 'Normal',
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_ingreso timestamptz NOT NULL DEFAULT now(),
  operario_asignado varchar(100),
  complejidad text NOT NULL DEFAULT 'Media' CHECK (complejidad IN ('Baja','Media','Alta')),
  sector text NOT NULL DEFAULT 'Taller Gráfico' CHECK (sector IN ('Taller Gráfico','Mostrador')),
  materiales text,
  hora_estimada_entrega time,
  hora_entrega_efectiva time,
  id_usuario_creador integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  usuario_trabajando_id integer,
  usuario_trabajando_nombre varchar(100),
  timestamp_inicio_trabajo timestamptz
);

CREATE INDEX IF NOT EXISTS idx_ordenes_fecha_estado ON public.ordenes_trabajo(fecha_creacion, estado);
CREATE INDEX IF NOT EXISTS idx_ordenes_estado_fecha ON public.ordenes_trabajo(estado, fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_ordenes_sector_fecha ON public.ordenes_trabajo(sector, fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_ordenes_complejidad ON public.ordenes_trabajo(complejidad);
CREATE INDEX IF NOT EXISTS idx_ordenes_operario_estado ON public.ordenes_trabajo(operario_asignado, estado);
CREATE INDEX IF NOT EXISTS idx_ordenes_cliente ON public.ordenes_trabajo(cliente);
CREATE INDEX IF NOT EXISTS idx_ordenes_prioridad_fecha ON public.ordenes_trabajo(prioridad, fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_usuario_trabajando ON public.ordenes_trabajo(usuario_trabajando_id, timestamp_inicio_trabajo);

CREATE TABLE IF NOT EXISTS public.historial_movimientos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  nombre_usuario varchar(100) NOT NULL,
  estado_anterior varchar(50),
  estado_nuevo varchar(50),
  duracion_estado_anterior_seg integer,
  "timestamp" timestamptz NOT NULL DEFAULT now(),
  comentario text
);

CREATE INDEX IF NOT EXISTS idx_historial_id_usuario ON public.historial_movimientos(id_usuario);
CREATE INDEX IF NOT EXISTS idx_historial_orden_timestamp ON public.historial_movimientos(id_orden, "timestamp");
CREATE INDEX IF NOT EXISTS idx_historial_estado_timestamp ON public.historial_movimientos(estado_nuevo, "timestamp");
CREATE INDEX IF NOT EXISTS idx_historial_usuario_timestamp ON public.historial_movimientos(nombre_usuario, "timestamp");
CREATE INDEX IF NOT EXISTS idx_historial_duracion ON public.historial_movimientos(duracion_estado_anterior_seg);
CREATE INDEX IF NOT EXISTS idx_historial_estado_anterior ON public.historial_movimientos(estado_anterior, "timestamp");

CREATE TABLE IF NOT EXISTS public.alertas_enviadas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  tipo_alerta text NOT NULL CHECK (tipo_alerta IN ('estancada','plazo')),
  "timestamp" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alerta_unica UNIQUE (id_orden, tipo_alerta)
);

CREATE TABLE IF NOT EXISTS public.archivos_adjuntos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  nombre_archivo varchar(255) NOT NULL,
  nombre_original varchar(255) NOT NULL,
  fecha_subida timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_archivos_orden ON public.archivos_adjuntos(id_orden);

CREATE TABLE IF NOT EXISTS public.comentarios_orden (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  comentario text NOT NULL,
  usuario_nombre varchar(255) NOT NULL,
  mencionados jsonb,
  "timestamp" timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_comentarios_orden ON public.comentarios_orden(id_orden);
CREATE INDEX IF NOT EXISTS idx_comentarios_usuario ON public.comentarios_orden(usuario_nombre);
CREATE INDEX IF NOT EXISTS idx_comentarios_timestamp ON public.comentarios_orden("timestamp");

CREATE TABLE IF NOT EXISTS public.enlaces_adjuntos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  titulo varchar(255) NOT NULL,
  url text NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_enlaces_orden ON public.enlaces_adjuntos(id_orden);

CREATE TABLE IF NOT EXISTS public.orden_materiales (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  id_material integer NOT NULL REFERENCES public.materiales(id) ON DELETE CASCADE,
  cantidad numeric(10,3) NOT NULL DEFAULT 1.000,
  CONSTRAINT orden_material_unica UNIQUE (id_orden, id_material)
);

CREATE INDEX IF NOT EXISTS idx_orden_materiales_orden ON public.orden_materiales(id_orden);
CREATE INDEX IF NOT EXISTS idx_orden_materiales_material ON public.orden_materiales(id_material);
CREATE INDEX IF NOT EXISTS idx_orden_materiales_cantidad ON public.orden_materiales(cantidad);

CREATE TABLE IF NOT EXISTS public.orden_sectores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  id_sector integer NOT NULL REFERENCES public.sectores(id) ON DELETE CASCADE,
  fecha_asignacion timestamptz DEFAULT now(),
  CONSTRAINT unique_orden_sector UNIQUE (id_orden, id_sector)
);

CREATE INDEX IF NOT EXISTS idx_orden_sectores_orden ON public.orden_sectores(id_orden);
CREATE INDEX IF NOT EXISTS idx_orden_sectores_sector ON public.orden_sectores(id_sector);

CREATE TABLE IF NOT EXISTS public.tareas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  descripcion_tarea varchar(255) NOT NULL,
  estado_kanban text NOT NULL DEFAULT 'Pendiente' CHECK (estado_kanban IN ('Pendiente','En Proceso','Finalizado'))
);

CREATE INDEX IF NOT EXISTS idx_tareas_orden ON public.tareas(id_orden);

-- =========================
-- Notificaciones y chat
-- =========================

CREATE TABLE IF NOT EXISTS public.chat_rooms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(255) NOT NULL,
  tipo text DEFAULT 'publico' CHECK (tipo IN ('publico','privado')),
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES public.chat_rooms(id) ON DELETE CASCADE ON UPDATE CASCADE,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  nombre_usuario varchar(100) NOT NULL,
  mensaje text NOT NULL,
  "timestamp" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_usuario ON public.chat_messages(id_usuario);
CREATE INDEX IF NOT EXISTS idx_chat_messages_room ON public.chat_messages(room_id);

CREATE TABLE IF NOT EXISTS public.notificaciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_destino varchar(255) NOT NULL,
  tipo varchar(50) NOT NULL DEFAULT 'mencion',
  mensaje text NOT NULL,
  id_orden integer REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  leida boolean DEFAULT false,
  "timestamp" timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario_leida ON public.notificaciones(usuario_destino, leida);
CREATE INDEX IF NOT EXISTS idx_notificaciones_timestamp ON public.notificaciones("timestamp");
CREATE INDEX IF NOT EXISTS idx_notificaciones_orden ON public.notificaciones(id_orden);

CREATE TABLE IF NOT EXISTS public.notificaciones_vistas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  id_historial integer NOT NULL,
  "timestamp" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT usuario_historial UNIQUE (id_usuario, id_historial)
);

CREATE TABLE IF NOT EXISTS public.user_notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  title varchar(255) NOT NULL,
  description text,
  type varchar(50) DEFAULT 'info',
  orden_id integer REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  is_read boolean DEFAULT false,
  "timestamp" timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_notifications_user_read ON public.user_notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_user_notifications_timestamp ON public.user_notifications("timestamp");

CREATE TABLE IF NOT EXISTS public.online_users (
  user_id integer PRIMARY KEY REFERENCES public.usuarios(id) ON DELETE CASCADE,
  user_nombre varchar(255) NOT NULL,
  last_seen timestamptz NOT NULL DEFAULT now()
);

-- =========================
-- Inteligencia / métricas
-- =========================

CREATE TABLE IF NOT EXISTS public.prediction_metrics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  numero_op varchar(50),
  tiempo_predicho_horas numeric(10,2),
  tiempo_real_horas numeric(10,2),
  confianza_prediccion integer,
  error_absoluto numeric(10,2),
  error_porcentual numeric(10,2),
  factores_aplicados text,
  fecha_prediccion timestamptz DEFAULT now(),
  fecha_completado timestamptz
);

CREATE INDEX IF NOT EXISTS idx_prediction_orden ON public.prediction_metrics(orden_id);
CREATE INDEX IF NOT EXISTS idx_prediction_fecha ON public.prediction_metrics(fecha_prediccion);
CREATE INDEX IF NOT EXISTS idx_prediction_completado ON public.prediction_metrics(fecha_completado);

CREATE TABLE IF NOT EXISTS public.smart_alerts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_alerta text NOT NULL CHECK (tipo_alerta IN ('retraso_predicho','sobrecarga_operario','cuello_botella','eficiencia_baja')),
  prioridad text NOT NULL CHECK (prioridad IN ('baja','media','alta','critica')),
  titulo varchar(255) NOT NULL,
  descripcion text,
  datos_contexto jsonb,
  fecha_creacion timestamptz DEFAULT now(),
  fecha_resuelto timestamptz,
  resuelto boolean DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_alerts_tipo ON public.smart_alerts(tipo_alerta, resuelto);
CREATE INDEX IF NOT EXISTS idx_alerts_prioridad ON public.smart_alerts(prioridad, fecha_creacion);

CREATE TABLE IF NOT EXISTS public.stats_cache (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cache_key varchar(255) NOT NULL,
  cache_data jsonb NOT NULL,
  created_at timestamptz DEFAULT now(),
  expires_at timestamptz NOT NULL,
  CONSTRAINT cache_key_unique UNIQUE (cache_key)
);

CREATE INDEX IF NOT EXISTS idx_cache_key_expires ON public.stats_cache(cache_key, expires_at);

CREATE TABLE IF NOT EXISTS public.trending_metrics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date NOT NULL,
  metrica varchar(100) NOT NULL,
  valor numeric(15,4) NOT NULL,
  categoria varchar(100),
  subcategoria varchar(100),
  created_at timestamptz DEFAULT now(),
  CONSTRAINT unique_metric_date UNIQUE (fecha, metrica, categoria, subcategoria)
);

CREATE INDEX IF NOT EXISTS idx_trending_fecha ON public.trending_metrics(fecha);
CREATE INDEX IF NOT EXISTS idx_trending_metrica ON public.trending_metrics(metrica, fecha);

-- =========================
-- Vista analítica
-- =========================

CREATE OR REPLACE VIEW public.v_ordenes_stats AS
SELECT
  ot.id,
  ot.numero_op,
  ot.cliente,
  ot.sector,
  ot.complejidad,
  ot.operario_asignado,
  ot.estado,
  ot.prioridad,
  ot.fecha_creacion,
  ot.fecha_entrega,
  (EXTRACT(EPOCH FROM (COALESCE(ot.fecha_entrega::timestamptz, now()) - ot.fecha_creacion)) / 3600.0) AS horas_transcurridas,
  CASE
    WHEN ot.estado = 'Entregado o Instalado'
      THEN (EXTRACT(EPOCH FROM (COALESCE(ot.fecha_entrega::timestamptz, now()) - ot.fecha_creacion)) / 3600.0)
    ELSE NULL
  END AS horas_completado,
  EXTRACT(WEEK FROM ot.fecha_creacion)::int AS semana_creacion,
  EXTRACT(YEAR FROM ot.fecha_creacion)::int AS anio_creacion,
  EXTRACT(MONTH FROM ot.fecha_creacion)::int AS mes_creacion,
  ((EXTRACT(DOW FROM ot.fecha_creacion)::int + 1)) AS dia_semana_creacion
FROM public.ordenes_trabajo ot;

-- =========================
-- Autenticación (RPC)
-- =========================

CREATE OR REPLACE FUNCTION public.login_usuario(p_usuario text, p_password text)
RETURNS TABLE (id integer, nombre text, rol text)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  user_rec public.usuarios%ROWTYPE;
BEGIN
  SELECT *
    INTO user_rec
    FROM public.usuarios
   WHERE lower(nombre) = lower(p_usuario)
   LIMIT 1;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  IF crypt(p_password, user_rec.password_hash) = user_rec.password_hash THEN
    RETURN QUERY SELECT user_rec.id, user_rec.nombre, user_rec.rol;
  END IF;
END;
$$;

-- Dar permisos para ejecutar la función
GRANT EXECUTE ON FUNCTION public.login_usuario(text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.login_usuario(text, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.logout_usuario()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  -- Placeholder para compatibilidad con el frontend
  RETURN;
END;
$$;

COMMIT;

