-- Script para crear la tabla user_notifications
-- Debe ejecutarse ANTES de crear los triggers

BEGIN;

-- Crear tabla user_notifications si no existe
CREATE TABLE IF NOT EXISTS public.user_notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  title varchar(255) NOT NULL,
  description text,
  type varchar(50) DEFAULT 'info' CHECK (type IN ('info', 'success', 'warning', 'error', 'mention', 'deadline')),
  orden_id integer,
  is_read boolean NOT NULL DEFAULT false,
  timestamp timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_user_notifications_user_id ON public.user_notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_user_notifications_is_read ON public.user_notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_user_notifications_timestamp ON public.user_notifications(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_user_notifications_orden_id ON public.user_notifications(orden_id);

-- Agregar foreign key a usuarios si la tabla existe
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'usuarios'
  ) THEN
    -- Verificar si la constraint ya existe
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints
      WHERE constraint_schema = 'public'
        AND table_name = 'user_notifications'
        AND constraint_name = 'user_notifications_user_id_fkey'
    ) THEN
      ALTER TABLE public.user_notifications
      ADD CONSTRAINT user_notifications_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;
      
      RAISE NOTICE '✅ Foreign key a usuarios agregada';
    END IF;
  ELSE
    RAISE WARNING '⚠️ Tabla usuarios no existe. Foreign key no agregada.';
  END IF;
END $$;

-- Agregar foreign key a ordenes_trabajo si la tabla existe
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'ordenes_trabajo'
  ) THEN
    -- Verificar si la constraint ya existe
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints
      WHERE constraint_schema = 'public'
        AND table_name = 'user_notifications'
        AND constraint_name = 'user_notifications_orden_id_fkey'
    ) THEN
      ALTER TABLE public.user_notifications
      ADD CONSTRAINT user_notifications_orden_id_fkey
      FOREIGN KEY (orden_id) REFERENCES public.ordenes_trabajo(id) ON DELETE SET NULL;
      
      RAISE NOTICE '✅ Foreign key a ordenes_trabajo agregada';
    END IF;
  ELSE
    RAISE WARNING '⚠️ Tabla ordenes_trabajo no existe. Foreign key no agregada.';
  END IF;
END $$;

-- Otorgar permisos
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_notifications TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_notifications TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE user_notifications_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE user_notifications_id_seq TO authenticated;

-- Verificar que la tabla existe
DO $$
DECLARE
  notifications_count integer;
BEGIN
  SELECT COUNT(*) INTO notifications_count FROM public.user_notifications;
  
  RAISE NOTICE '✅ Tabla user_notifications creada/verificada';
  RAISE NOTICE '   Total de notificaciones: %', notifications_count;
END $$;

COMMIT;

