-- Script para crear la tabla ordenes_trabajo si no existe
-- Basado en schema.sql pero seguro para ejecutar múltiples veces

BEGIN;

-- Crear tabla ordenes_trabajo si no existe
CREATE TABLE IF NOT EXISTS public.ordenes_trabajo (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_op varchar(255) NOT NULL,
  cliente varchar(255) NOT NULL,
  descripcion text,
  fecha_entrega date NOT NULL,
  estado varchar(50) NOT NULL DEFAULT 'Pendiente',
  prioridad varchar(50) NOT NULL DEFAULT 'Normal',
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_ingreso timestamptz NOT NULL DEFAULT now(),
  operario_asignado varchar(100),
  complejidad text NOT NULL DEFAULT 'Media' CHECK (complejidad IN ('Baja','Media','Alta')),
  sector text NOT NULL DEFAULT 'Diseño Gráfico' CHECK (
    sector IN (
      'Diseño Gráfico',
      'Taller de Imprenta',
      'Taller Gráfico',
      'Instalaciones',
      'Metalúrgica',
      'Mostrador',
      'Caja'
    )
  ),
  materiales text,
  hora_estimada_entrega time,
  hora_entrega_efectiva time,
  id_usuario_creador integer,
  nombre_creador varchar(100),
  foto_url text,
  usuario_trabajando_id integer,
  usuario_trabajando_nombre varchar(100),
  timestamp_inicio_trabajo timestamptz,
  -- Campos de contacto (agregados aquí directamente)
  telefono_cliente text,
  email_cliente text,
  direccion_cliente text,
  whatsapp_link text,
  ubicacion_link text,
  drive_link text,
  dni_cuit text
);

-- Agregar foreign key a usuarios si la tabla usuarios existe
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'usuarios'
  ) THEN
    -- Verificar si la constraint ya existe
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints
      WHERE constraint_schema = 'public'
        AND table_name = 'ordenes_trabajo'
        AND constraint_name = 'ordenes_trabajo_id_usuario_creador_fkey'
    ) THEN
      ALTER TABLE public.ordenes_trabajo
        ADD CONSTRAINT ordenes_trabajo_id_usuario_creador_fkey
        FOREIGN KEY (id_usuario_creador) REFERENCES public.usuarios(id) ON DELETE SET NULL;
    END IF;
  END IF;
END $$;

-- Crear índices si no existen
CREATE INDEX IF NOT EXISTS idx_ordenes_fecha_estado ON public.ordenes_trabajo(fecha_creacion, estado);
CREATE INDEX IF NOT EXISTS idx_ordenes_estado_fecha ON public.ordenes_trabajo(estado, fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_ordenes_sector_fecha ON public.ordenes_trabajo(sector, fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_ordenes_complejidad ON public.ordenes_trabajo(complejidad);
CREATE INDEX IF NOT EXISTS idx_ordenes_operario_estado ON public.ordenes_trabajo(operario_asignado, estado);
CREATE INDEX IF NOT EXISTS idx_ordenes_cliente ON public.ordenes_trabajo(cliente);
CREATE INDEX IF NOT EXISTS idx_ordenes_prioridad_fecha ON public.ordenes_trabajo(prioridad, fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_usuario_trabajando ON public.ordenes_trabajo(usuario_trabajando_id, timestamp_inicio_trabajo);

-- Agregar columnas de contacto si no existen (por si la tabla ya existía sin ellas)
DO $$
BEGIN
  -- Telefono cliente
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'ordenes_trabajo'
      AND column_name = 'telefono_cliente'
  ) THEN
    ALTER TABLE public.ordenes_trabajo ADD COLUMN telefono_cliente text;
  END IF;

  -- Email cliente
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'ordenes_trabajo'
      AND column_name = 'email_cliente'
  ) THEN
    ALTER TABLE public.ordenes_trabajo ADD COLUMN email_cliente text;
  END IF;

  -- Direccion cliente
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'ordenes_trabajo'
      AND column_name = 'direccion_cliente'
  ) THEN
    ALTER TABLE public.ordenes_trabajo ADD COLUMN direccion_cliente text;
  END IF;

  -- WhatsApp link
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'ordenes_trabajo'
      AND column_name = 'whatsapp_link'
  ) THEN
    ALTER TABLE public.ordenes_trabajo ADD COLUMN whatsapp_link text;
  END IF;

  -- Ubicacion link
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'ordenes_trabajo'
      AND column_name = 'ubicacion_link'
  ) THEN
    ALTER TABLE public.ordenes_trabajo ADD COLUMN ubicacion_link text;
  END IF;

  -- Drive link
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'ordenes_trabajo'
      AND column_name = 'drive_link'
  ) THEN
    ALTER TABLE public.ordenes_trabajo ADD COLUMN drive_link text;
  END IF;

  -- DNI/CUIT
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'ordenes_trabajo'
      AND column_name = 'dni_cuit'
  ) THEN
    ALTER TABLE public.ordenes_trabajo ADD COLUMN dni_cuit text;
  END IF;
END $$;

COMMIT;

-- Verificar que todo se creó correctamente
SELECT 
  'Tabla creada' as status,
  COUNT(*) as total_columnas
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'ordenes_trabajo';

