-- Script para asegurar que la tabla usuarios existe
-- Basado en schema.sql

BEGIN;

-- Crear tabla usuarios si no existe
CREATE TABLE IF NOT EXISTS public.usuarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(255) NOT NULL UNIQUE,
  password_hash text NOT NULL,
  rol varchar(50) NOT NULL CHECK (
    rol IN (
      'administracion',
      'gerencia',
      'recursos-humanos',
      'diseno',
      'imprenta',
      'taller-grafico',
      'instalaciones',
      'metalurgica',
      'caja',
      'mostrador'
    )
  ),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Crear índice si no existe
CREATE INDEX IF NOT EXISTS idx_usuarios_nombre ON public.usuarios(nombre);
CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON public.usuarios(rol);

-- Otorgar permisos
GRANT SELECT, INSERT, UPDATE, DELETE ON public.usuarios TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.usuarios TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE usuarios_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE usuarios_id_seq TO authenticated;

-- Verificar que la tabla existe y mostrar información
DO $$
DECLARE
  usuarios_count integer;
BEGIN
  SELECT COUNT(*) INTO usuarios_count FROM public.usuarios;
  
  RAISE NOTICE '✅ Tabla usuarios verificada';
  RAISE NOTICE '   Total de usuarios: %', usuarios_count;
  
  IF usuarios_count = 0 THEN
    RAISE WARNING '⚠️ La tabla usuarios está vacía. Los triggers de notificaciones necesitan usuarios para funcionar.';
    RAISE NOTICE '💡 Puedes crear usuarios usando la función crear_usuario() o desde la interfaz de la app.';
  END IF;
END $$;

COMMIT;

